name: Parsa
avatar: images/avatar.png # Avatar image. Default to "images/profile.webp".
bio: 'Python (Flask) and Flutter coder, also exploring Rust. Passionate about building dynamic web apps and sleek static sites with a friendly touch.'
location: Tehran # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  email: iknowarch@proton.me
  github: parsamrrelax
  twitter: maybeparsa

